services:
  web:
    image: php:8.2-apache  
    build: .
    container_name: damaweb
    ports:
      - "9999:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      
  db:
    image: mysql:latest
    container_name: damadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mvc
      MYSQL_USER: dama
      MYSQL_PASSWORD: 1234

    volumes:
      - db_data:/var/lib/mysql
      - ./sql/base.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
